apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejs-deployment
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 2
      maxUnavailable: 0
  selector:
    matchLabels:
      app: nodejs
  template:
    metadata:
      labels:
        app: nodejs
    spec:
      containers:
        - name: node-server
          image: aymenalatri/node_image:first
          imagePullPolicy: Always
          ports:
            - name: node
              containerPort: 8080
              protocol: TCP
        - name: mongo-db
          image: aymenalatri/mongo_db:first
          imagePullPolicy: Always
          ports:
            - name: mongo
              containerPort: 27017
              protocol: TCP
